import type { Metadata } from 'next';
import Providers from './providers';
import { ProvidersTwo } from './GlobalRedux/provider';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ProvidersTwo>
          <Providers>
            {children}
          </Providers>
        </ProvidersTwo>
      </body>
    </html>
  )
}
